# Generated by Django 4.2.1 on 2023-05-14 13:11

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_img_profile_images_alter_profile_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='images',
            field=models.ImageField(default='defaulet-avatar.jpg', upload_to='user-image'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user_id',
            field=models.UUIDField(default=uuid.UUID('19f52085-7dff-4f2f-badf-7a36fd129b2a')),
        ),
    ]
