# Generated by Django 4.2.1 on 2023-05-14 13:11

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_profile_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='user_id',
            field=models.UUIDField(default=uuid.UUID('80868c94-078e-4f23-95a9-25678c9d70ed')),
        ),
    ]
