# Generated by Django 4.2.1 on 2023-06-11 11:37

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_post_alter_profile_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_id', models.CharField(max_length=50)),
                ('user', models.CharField(max_length=90)),
            ],
        ),
        migrations.AlterField(
            model_name='profile',
            name='user_id',
            field=models.UUIDField(default=uuid.UUID('ec35a6e5-ddee-47ed-adaa-154f309274f9')),
        ),
    ]
